!function () {
  try {
    var e = "undefined" != typeof window ? window : "undefined" != typeof global ? global : "undefined" != typeof globalThis ? globalThis : "undefined" != typeof self ? self : {},
      n = new e.Error().stack;
    n && (e._sentryDebugIds = e._sentryDebugIds || {}, e._sentryDebugIds[n] = "8a5f3e81-5d7f-5c57-9071-ca70f3e2bc21");
  } catch (e) {}
}();
export const id = 4;
export const ids = [4];
export const modules = {
  2237: (HH, IH, EH) => {
    EH.r(IH), EH.d(IH, {
      solidIcons: () => KR
    });
    var RH = EH(2245),
      hH = EH(2256),
      TH = EH(2262),
      sH = EH(2265),
      eH = EH(2259),
      GH = EH(2271),
      AH = EH(2273),
      VH = EH(2281),
      YH = EH(2293),
      QH = EH(2302),
      JH = EH(2309),
      OH = EH(2289),
      rH = EH(2311),
      FH = EH(2320),
      MH = EH(2325),
      NH = EH(2333),
      iI = EH(2342),
      DH = EH(2345),
      PH = EH(2350),
      XH = EH(2359),
      mI = EH(2361),
      ZH = EH(2369),
      qH = EH(2376),
      LH = EH(2379),
      gH = EH(2382),
      yH = EH(2389),
      oH = EH(2396),
      kI = EH(2400),
      CH = EH(2409),
      cH = EH(2415),
      UH = EH(2421),
      WH = EH(2424),
      BH = EH(2436),
      fH = EH(2444),
      aH = EH(2448),
      nH = EH(2454),
      pH = EH(2460),
      dH = EH(2463),
      uH = EH(2472),
      lH = EH(2478),
      KH = EH(2480),
      wH = EH(2485),
      zH = EH(2489),
      tH = EH(2492),
      jI = EH(2509),
      vH = EH(2511),
      bH = EH(2519),
      SH = EH(2527),
      xH = EH(2533),
      HI = EH(2538),
      II = EH(2553),
      EI = EH(2559),
      RI = EH(2568),
      hI = EH(2571),
      TI = EH(2585),
      sI = EH(2593),
      eI = EH(2597),
      GI = EH(2605),
      AI = EH(2609),
      VI = EH(2515),
      YI = EH(2614),
      QI = EH(2622),
      JI = EH(2626),
      OI = EH(2633),
      rI = EH(2637),
      FI = EH(2642),
      MI = EH(2654),
      NI = EH(2648),
      iE = EH(2666),
      DI = EH(2671),
      PI = EH(2677),
      XI = EH(2684),
      mE = EH(2693),
      ZI = EH(2702),
      qI = EH(2705),
      LI = EH(2431),
      gI = EH(2711),
      yI = EH(2718),
      oI = EH(2722),
      kE = EH(2726),
      CI = EH(2688),
      cI = EH(2731),
      UI = EH(2733),
      WI = EH(2735),
      BI = EH(2738),
      fI = EH(2741),
      aI = EH(2743),
      nI = EH(2750),
      pI = EH(2756),
      dI = EH(2762),
      uI = EH(2767),
      lI = EH(2770),
      KI = EH(2754),
      wI = EH(2779),
      zI = EH(2784),
      tI = EH(2792),
      jE = EH(2795),
      vI = EH(2804),
      bI = EH(2813),
      SI = EH(2816),
      xI = EH(2820),
      HE = EH(2827),
      IE = EH(2835),
      EE = EH(2843),
      RE = EH(2849),
      hE = EH(2854),
      TE = EH(2859),
      sE = EH(2869),
      eE = EH(2878),
      GE = EH(2881),
      AE = EH(2885),
      VE = EH(2891),
      YE = EH(2902),
      QE = EH(2904),
      JE = EH(2912),
      OE = EH(2919),
      rE = EH(2924),
      FE = EH(2926),
      ME = EH(2933),
      NE = EH(2660),
      iR = EH(2942),
      DE = EH(2951),
      PE = EH(2953),
      XE = EH(2546),
      mR = EH(2864),
      ZE = EH(2959),
      qE = EH(2962),
      LE = EH(2971),
      gE = EH(2975),
      yE = EH(2978),
      oE = EH(2254),
      kR = EH(2986),
      CE = EH(2994),
      cE = EH(3003),
      UE = EH(3010),
      WE = EH(3024),
      BE = EH(3027),
      fE = EH(3029),
      aE = EH(3037),
      nE = EH(3017),
      pE = EH(2500),
      dE = EH(3046),
      uE = EH(3051),
      lE = EH(3053),
      KE = EH(3061),
      wE = EH(3056),
      zE = EH(3069),
      tE = EH(3078),
      jR = EH(3084),
      vE = EH(3090),
      bE = EH(3092),
      SE = EH(3101),
      xE = EH(3103),
      HR = EH(3107),
      IR = EH(3110),
      ER = EH(2893),
      RR = EH(3112),
      hR = EH(3114),
      TR = EH(3120),
      sR = EH(3129),
      eR = EH(3134),
      GR = EH(3137),
      AR = EH(3142),
      VR = EH(3144),
      YR = EH(3151),
      QR = EH(3160),
      JR = EH(2576),
      OR = EH(3166),
      rR = EH(3170),
      FR = EH(3177),
      MR = EH(3183),
      NR = EH(3186),
      ih = EH(3190),
      DR = EH(3198),
      PR = EH(3202),
      XR = EH(3207),
      mh = EH(3213),
      ZR = EH(3220),
      qR = EH(3223),
      LR = EH(3230),
      gR = EH(3238),
      yR = EH(3245),
      oR = EH(3254),
      kh = EH(3263),
      CR = EH(3265),
      cR = EH(3270),
      UR = EH(3275),
      WR = EH(3280),
      BR = EH(3286),
      fR = EH(3293),
      aR = EH(3298),
      nR = EH(3306),
      pR = EH(3308),
      dR = EH(3314),
      uR = EH(3321),
      lR = EH(3328);
    const KR = {
      add: RH.d,
      "angle-double-up": hH.h,
      "angle-down": TH.e,
      "angle-up": sH.h,
      "angles-up": eH.faAnglesUp,
      "arrow-up": GH.h,
      "arrow-up-right-from-square": AH.faArrowUpRightFromSquare,
      arrows: VH.f,
      "arrows-h": YH.e,
      "arrows-left-right": QH.faArrowsLeftRight,
      "arrows-rotate": JH.faArrowsRotate,
      "arrows-up-down-left-right": OH.faArrowsUpDownLeftRight,
      award: rH.f,
      backpack: FH.c,
      bars: MH.faBars,
      bee: NH.f,
      "block-question": iI.g,
      bolt: DH.faBolt,
      boot: PH.f,
      calendar: XH.d,
      "caret-up": mI.h,
      "cart-shopping": ZH.faCartShopping,
      check: qH.g,
      "chess-knight": LH.e,
      "chess-rook": gH.f,
      "child-reaching": yH.c,
      "circle-check": oH.g,
      "circle-info": kI.faCircleInfo,
      "circle-plus": CH.faCirclePlus,
      "circle-xmark": cH.h,
      "clock-rotate-left": UH.faClockRotateLeft,
      cog: WH.c,
      coins: BH.h,
      "comment-dots": fH.faCommentDots,
      commenting: aH.f,
      compress: nH.f,
      "computer-mouse": pH.faComputerMouse,
      cookie: dH.h,
      copy: uH.f,
      crosshairs: lH.g,
      crown: KH.g,
      cube: wH.f,
      cubes: zH.g,
      cut: tH.f,
      dice: jI.h,
      dizzy: vH.f,
      "door-closed": bH.i,
      "door-open": SH.g,
      download: xH.d,
      edit: HI.d,
      ellipsis: II.faEllipsis,
      "ellipsis-h": EI.e,
      exclamation: RI.g,
      "exclamation-triangle": hI.d,
      expand: TI.c,
      "external-link": sI.f,
      eye: eI.i,
      "eye-slash": GI.g,
      "face-diagonal-mouth": AI.f,
      "face-dizzy": VI.faFaceDizzy,
      "face-raised-eyebrow": YI.f,
      "face-smile": QI.faFaceSmile,
      "face-worried": JI.e,
      "feather-alt": OI.d,
      "feather-pointed": rI.faFeatherPointed,
      "file-alt": FI.g,
      "file-clipboard": MI.e,
      "file-lines": NI.faFileLines,
      "file-text": iE.d,
      film: DI.h,
      fire: PI.f,
      "fist-raised": XI.e,
      flag: mE.i,
      "folder-image": ZI.f,
      "gauge-high": qI.faGaugeHigh,
      gear: LI.faGear,
      gem: gI.f,
      globe: yI.h,
      hammer: oI.g,
      "hand-back-point-up": kE.h,
      "hand-fist": CI.faHandFist,
      "hand-holding-medical": cI.d,
      "hand-point-left": UI.g,
      "hand-wave": WI.h,
      "hands-clapping": BI.h,
      "hat-witch": fI.g,
      heart: aI.g,
      "heart-music-camera-bolt": nI.i,
      history: pI.d,
      hourglass: dI.faHourglass,
      "hourglass-clock": uI.f,
      "hourglass-empty": lI.h,
      icons: KI.faIcons,
      image: wI.h,
      "image-slash": zI.f,
      "info-circle": tI.e,
      joystick: jE.i,
      "layer-group": vI.e,
      lightbulb: bI.g,
      list: SI.faList,
      "list-squares": xI.d,
      "location-check": HE.faLocationCheck,
      "location-xmark": IE.faLocationXmark,
      lock: EE.g,
      "lock-open": RE.e,
      "magnifying-glass": hE.faMagnifyingGlass,
      male: TE.d,
      "map-marker-check": sE.e,
      "map-marker-times": eE.i,
      "map-marker-xmark": GE.e,
      minus: AE.faMinus,
      "minus-square": VE.h,
      mouse: YE.f,
      music: QE.e,
      "music-slash": JE.h,
      navicon: OE.f,
      palette: rE.f,
      pants: FE.h,
      "party-horn": ME.e,
      paste: NE.faPaste,
      pause: iR.f,
      pen: DE.i,
      "pen-field": PE.d,
      "pen-to-square": XE.faPenToSquare,
      person: mR.faPerson,
      "person-arrow-down-to-line": ZE.g,
      "person-arrow-up-from-line": qE.f,
      "person-falling-burst": LE.h,
      "person-military-pointing": gE.i,
      play: yE.f,
      plus: oE.faPlus,
      "plus-circle": kR.e,
      "power-off": CE.d,
      recycle: cE.f,
      "redo-alt": UE.g,
      refresh: WE.f,
      "right-from-bracket": BE.faRightFromBracket,
      "rocket-launch": fE.f,
      "rotate-forward": aE.e,
      "rotate-right": nE.faRotateRight,
      scissors: pE.faScissors,
      search: dE.e,
      shield: uE.faShield,
      "shield-alt": lE.d,
      "shield-blank": KE.d,
      "shield-halved": wE.faShieldHalved,
      shirt: zE.h,
      shoe: tE.f,
      "shopping-cart": jR.g,
      "sign-out-alt": vE.f,
      skull: bE.g,
      smile: SE.c,
      snowflake: xE.h,
      "square-dashed": IR.h,
      "square-minus": ER.faSquareMinus,
      star: RR.e,
      "star-christmas": HR.f,
      store: hR.f,
      subtract: TR.i,
      swords: sR.e,
      sync: eR.f,
      "t-shirt": lR.c,
      "tachometer-alt": GR.h,
      "tachometer-alt-fast": AR.g,
      terminal: VR.g,
      "trash-alt": YR.f,
      "trash-can": QR.faTrashCan,
      "triangle-exclamation": JR.faTriangleExclamation,
      trophy: OR.d,
      tshirt: lR.g,
      "up-from-bracket": rR.e,
      upload: FR.f,
      user: MR.f,
      "user-astronaut": NR.e,
      "user-friends": ih.g,
      "user-group": DR.faUserGroup,
      "user-group-crown": PR.faUserGroupCrown,
      "user-minus": XR.e,
      "user-plus": mh.f,
      "user-slash": ZR.c,
      "user-unlock": qR.c,
      "users-crown": LR.e,
      video: gR.faVideo,
      "video-camera": yR.f,
      volume: oR.faVolume,
      "volume-down": kh.h,
      "volume-low": CR.faVolumeLow,
      "volume-medium": cR.c,
      "volume-slash": UR.e,
      warning: WR.h,
      wifi: BR.faWifi,
      "wifi-3": fR.e,
      "wifi-strong": aR.g,
      wrench: nR.g,
      x: pR.g,
      xmark: dR.g,
      zap: uR.d
    };
  }
};
//# sourceMappingURL=ug4nu.icons-solid.0fafc311.chunk.js.map
//# debugId=8a5f3e81-5d7f-5c57-9071-ca70f3e2bc21